### ISSUE TITLE
При ошибках в запросе создания заказа не заполняется массив errorы у класса ApiReponse

### ISSUE THREAD

**Issue by HueJack** [cdek-it/sdk2.0#11]
В ответ от системы приходит массив 'requests' => [ ['errors' => []]; https://monosnap.com/file/JgGfDwQr6YvZahMbn2e7QBXS9VXzom , скрипт ищет errors без вложенности /src/Http/ApiResponse.php:58

**Comment by pozdeiev** [comment]
Всё ещё актуально.

**Comment by TTATPuOT** [comment]
Исправил эту проблему в [своём форке](https://github.com/TTATPuOT/cdek-sdk2.0) этой библиотеки в версии 1.0.1
