### ISSUE TITLE
Как получить цену доставки в определенный город и/или ПВЗ?

### ISSUE THREAD

**Issue by KoIIIeY** [cdek-it/sdk2.0#15]
Как получить цену доставки в определенный город и/или ПВЗ?

**Comment by vodnicearv** [comment]
https://confluence.cdek.ru/pages/viewpage.action?pageId=63345519

пока что только так

**Comment by KoIIIeY** [comment]
Я так и сделал в итоге :D 
Взял токен из sdk и сделал запрос напрямую.
