### ISSUE TITLE
php8.0 не подходит под зависимости

### ISSUE THREAD

**Issue by politsin** [cdek-it/sdk2.0#16]
Добрый день!
В файле `composer.json` указана версия `"php": "^7.1"`
Такое определение версии не даёт использовать его с php8

28 ноября 2021 года php7 не будет актуальной версией
смори `php live circle` https://www.php.net/supported-versions.php

Давайте заменим на `"php": "^7.4 || ^8.0"`, или хотябы на `"php": "^7.1 || ^8.0"`,

**Comment by ilyavaiser** [comment]
Алеу, живые есть?

**Comment by politsin** [comment]
общая идеология на всю компанию :(

**Comment by evilless63** [comment]
Да форкни его себе и все)

**Comment by politsin** [comment]
мне за державу обидно

**Comment by politsin** [comment]
подождём ещё 😂

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
7.4 | 28 Nov 2019 | 2 years, 4 months ago | 28 Nov 2021 | 4 months ago | 28 Nov 2022 | in 7 months
8.0 | 26 Nov 2020 | 1 year, 4 months ago | 26 Nov 2022 | in 7 months | 26 Nov 2023 | in 1 year, 7 months
8.1 | 25 Nov 2021 | 4 months ago | 25 Nov 2023 | in 1 year, 7 months | 25 Nov 2024 | in 2 years, 7 months

**Comment by motoroller1983** [comment]
Живые то есть? будете будут версии менять?

**Comment by tezrik** [comment]
Я так понимаю что бы работало надо дописать самому ))))

**Comment by politsin** [comment]
Скоро уже `28 Nov 2022` когда php 7 канет в лету

**Comment by politsin** [comment]
Теперь уже официально!
PHP-7+ ВСЁ! Пара-пара-пам!
End of life
https://www.php.net/supported-versions.php

**Comment by TTATPuOT** [comment]
[Создал форк](https://github.com/TTATPuOT/cdek-sdk2.0) этой библиотеки с поддержкой 8.0+
Так как необходимость есть, а авторы оригинальна пропали с радаров.

Установить можно через
```
composer require ttatpuot/cdek-sdk2.0
```
Обратная совместимость сохраняется, переписывать ничего не нужно.

**Comment by iamwildtuna** [comment]
@TTATPuOT молодцом!

**Comment by politsin** [comment]
Я всётаки надеюсь на сдек! это же серъёзная контора, а не ларёк с шаурмой! 😆

**Comment by adamasantares** [comment]
@politsin понадеялись и хватит :) пора делать форки

**Comment by vermorag** [comment]
https://github.com/cdek-it/sdk2.0/blob/master/composer.json#L33
