### ISSUE TITLE
Калькулятор

### ISSUE THREAD

**Issue by demian18** [cdek-it/sdk2.0#17]
Здравствуйте, вы не планируете добавлять функцию по обращению к калькулятору СДЭК? Или для этого уже есть решение? Спасибо!)

**Comment by TTATPuOT** [comment]
[Создал форк](https://github.com/TTATPuOT/cdek-sdk2.0) этой библиотеки с поддержкой метода [Расчета по доступным тарифам](https://api-docs.cdek.ru/63345519.html)
Так как необходимость есть, а авторы оригинальна пропали с радаров.

Установить можно через
```
composer require ttatpuot/cdek-sdk2.0
```
Обратная совместимость сохраняется, переписывать ничего не нужно.

**Comment by vermorag** [comment]
https://github.com/cdek-it/sdk2.0/blob/master/src/Actions/Calculator.php#L35
