### ISSUE TITLE
Новые значения фильтра в экшене офисов

### ISSUE THREAD

**Issue by aavday** [cdek-it/sdk2.0#20]
В экшене офисов стоит добавить фильтры is_handout, is_reception и fias_guid, которых сейчас нет

**Comment by TTATPuOT** [comment]
Добавил новые значения фильтров в [своём форке](https://github.com/TTATPuOT/cdek-sdk2.0) этой библиотеки в версии 1.0.1

**Comment by vermorag** [comment]
Исправлено.
https://github.com/cdek-it/sdk2.0/blob/master/src/Actions/Offices.php#L39
