### ISSUE TITLE
Неверное название пакета composer в документации

### ISSUE THREAD

**Issue by nb-nortus** [cdek-it/sdk2.0#28]
Добрый день! В Вашей документации по адресу https://github.com/cdek-it/sdk2.0/blob/master/docs/index.md указано неверное название пакета composer, из-за чего возникает ошибка установки пакета, если сразу провалиться в документацию и следовать её инструкциям. Верное название нашёл на главной странице проекта в описании) Поправьте, пожалуйста, ```composer require cdek-it/cdek-sdk2.0``` на ```composer require cdek-it/sdk2.0```

**Comment by vermorag** [comment]
Документация перенесена на [вики](https://github.com/cdek-it/sdk2.0/wiki)
