### ISSUE TITLE
Тестовые данные

### ISSUE THREAD

**Issue by lyalin-nick** [cdek-it/sdk2.0#30]
При использовании функции setTest() у клиента CdekSDK2\Http\Api в параметры **account** и **secure** устанавливаются константы CdekSDK2\Constants::TEST_ACCOUNT и CdekSDK2\Constants::TEST_SECURE соответственно. Но данные в этих константах не соответствуют данным тестовый учетной записи в доке https://api-docs.cdek.ru/29923849.html

![image](https://github.com/user-attachments/assets/039214b8-c222-4921-8f18-6afcca436366)

**Comment by vermorag** [comment]
Тестовые данные были актуализированы на прошлой неделе
https://github.com/cdek-it/sdk2.0/blob/master/src/Constants.php#L281
