### ISSUE TITLE
Заменить тестовые доступы

### ISSUE THREAD

**Issue by bereza-evgenij** [cdek-it/sdk2.0#5]
У cdek поменялись тестовые доступы https://confluence.cdek.ru/pages/viewpage.action?pageId=29923849, поменяйте их, пожалуйста. А лучше реализуйте возможность программного переопределения тестовых доступов

**Comment by bereza-evgenij** [comment]
Выкрутился таким способом:
`$client->setTest(true);`
`$client->setAccount('EMscd6r9JnFiQ3bLoyjJY6eM78JrJceI');`
`$client->setSecure('PjLZkKBHEiLK3YsjtNrt3TGNG0ahs3kG');`

**Comment by ihomyak** [comment]
Исправил в версии 0.1.3

**Comment by ihomyak** [comment]
Исправил в версии 0.1.3
