### ISSUE TITLE
Invalid value [null] in [seller.phone] parameter

### ISSUE THREAD

**Issue by filinme** [cdek-it/sdk2.0#6]
В классе BaseTypes/Seller некорректно указан тип поля $phone, из-за чего в запросе к серверу уходит нулевое значение seller.phone и возникает ошибка "Invalid value [null] in [seller.phone] parameter".
Корректное значение:
@Type("string")
@var string

**Comment by ihomyak** [comment]
Исправлено в версии 0.1.3
